language: ruby
before_install: gem install bundler -v 1.17.3
rvm:
 - 2.1
 - 2.2
 - 2.3.0
matrix:
deploy:
  gem: mollie-api-ruby
  provider: rubygems
  api_key:
    secure: "JdYKjK+AZNNviyAW92ta16Kk/u1gLTyvUVjoiSrGchsMmx8pN107MERpn5klFzOTKcnmMn+h3eA0RzhsuA+eFBfd5X58kNlXzXzKzKvOKmjrH69jiUWAJ5PmepacvsKMCAovOOtkskFzifKUUkrkPv87KO1J97wsZ4ASX6q3MRs="
  on:
    tags: true
    repo: mollie/mollie-api-ruby
    rvm: 2.3.0
